-- Create tours table
create table if not exists public.tours (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null,
  price numeric not null,
  duration text not null,
  image text not null,
  description text not null,
  featured boolean default false,
  destination text not null,
  accommodation text,
  meals text,
  transport text,
  itinerary jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.tours enable row level security;

-- Drop existing select policy if any, then create public read policy
drop policy if exists "Allow public select access" on public.tours;
create policy "Allow public select access" on public.tours for select using (true);

-- Insert tour packages seed data
insert into public.tours (slug, name, category, price, duration, image, description, featured, destination, accommodation, meals, transport, itinerary)
values
  (
    'genting-highlands',
    '3D2N Genting Highlands Getaway',
    'malaysian',
    399,
    '3 Days, 2 Nights',
    '/images/locations/genting.jpg',
    'Escape to the cooling mountain resort of Genting Highlands. Experience theme parks, shopping, and high-altitude entertainment.',
    true,
    'Pahang, Malaysia',
    '4-Star Resort Hotel',
    'Daily Breakfast',
    'Return Shuttle Bus & Cable Car',
    '[
      {"day": 1, "title": "Arrival & Awana Skyway", "desc": "Depart from Kuala Lumpur and transfer to Genting Highlands. Enjoy a scenic ride on the Awana Skyway cable car, taking in the panoramic mountain breeze. Check in and spend your evening exploring SkyAvenue mall."},
      {"day": 2, "title": "SkyWorlds Theme Park Adventure", "desc": "Spend a thrilling day at Genting SkyWorlds Theme Park. Discover 9 uniquely themed worlds with state-of-the-art rides, dining, and live entertainment suitable for all ages."},
      {"day": 3, "title": "Premium Outlets & Departure", "desc": "Check out and head to the Genting Highlands Premium Outlets for a morning of shopping. Transfer back to Kuala Lumpur in the afternoon."}
    ]'::jsonb
  ),
  (
    'gua-mulu',
    '5D4N Gua Mulu Cave Adventure',
    'malaysian',
    899,
    '5 Days, 4 Nights',
    '/images/locations/mulu.jpg',
    'Explore the UNESCO World Heritage Mulu Caves. Walk through massive chambers and hike the spectacular razor-sharp pinnacles.',
    true,
    'Sarawak, Malaysia',
    'Park Bungalows / Mulu Marriott',
    'Full Board (Breakfast, Lunch, Dinner)',
    'Longboat River Transfers & Guided Walks',
    '[
      {"day": 1, "title": "Arrival & Deer & Lang Caves", "desc": "Arrive at Mulu Airport and transfer to your lodge. In the afternoon, take a scenic jungle walk to explore Lang''s Cave and the massive Deer Cave. Witness the spectacular bat exodus at dusk."},
      {"day": 2, "title": "Wind Cave & Clearwater Cave", "desc": "Board a traditional longboat up the Melinau River. Stop at Wind Cave to marvel at delicate stalactites, then visit Clearwater Cave to see the subterranean river systems. Enjoy a picnic lunch and swim in the spring waters."},
      {"day": 3, "title": "Mulu Canopy Skywalk", "desc": "Experience the world''s longest tree-based canopy walk. Stroll 15 meters above the forest floor and spot unique birds, orchids, and canopy wildlife."},
      {"day": 4, "title": "Fast Lane Adventure Trek", "desc": "Embark on a challenging trek to the Fast Lane section of Lagangs Cave. Learn about cave geology and admire the unique rock formations."},
      {"day": 5, "title": "Departure", "desc": "Leisurely morning around the resort. Check out and transfer to Mulu Airport for your flight home."}
    ]'::jsonb
  ),
  (
    'johor',
    '4D3N Johor Heritage & Parks',
    'malaysian',
    499,
    '4 Days, 3 Nights',
    '/images/locations/johor.jpg',
    'Perfect family fun at Legoland and Desaru Coast. Discover historical heritage and delicious southern culinary delights.',
    false,
    'Johor, Malaysia',
    '4-Star City/Theme Park Hotel',
    'Daily Breakfast & 1 Local Dinner',
    'Private Ground Transfers',
    '[
      {"day": 1, "title": "Arrival & Johor Bahru City Tour", "desc": "Arrive in JB and check in. Visit the beautiful Sultan Abu Bakar State Mosque, take a walk down Tan Hiok Nee Heritage Street, and enjoy local street food."},
      {"day": 2, "title": "Legoland Malaysia Resort", "desc": "Enjoy a full day at Legoland Theme Park and Water Park. Experience interactive rides, shows, and LEGO building workshops, fun for the whole family."},
      {"day": 3, "title": "Desaru Coast Beach Escape", "desc": "Drive to Desaru Coast. Spend the day relaxing on sandy beaches, visiting the local fruit farm, or visiting the Desaru Coast Adventure Waterpark."},
      {"day": 4, "title": "Shopping at JPO & Departure", "desc": "Visit Johor Premium Outlets (JPO) for discounted luxury shopping. Transfer to the airport/station for departure."}
    ]'::jsonb
  ),
  (
    'kota-kinabalu',
    '5D4N Kota Kinabalu Mount Climb',
    'malaysian',
    1199,
    '5 Days, 4 Nights',
    '/images/locations/kinabalu.jpg',
    'Climb Mount Kinabalu, witness breathtaking peak sunrises, and relax on beautiful sandy islands of Sabah.',
    false,
    'Sabah, Malaysia',
    'Mountain Huts & KK Hotel',
    'Full Board on Climb Days, Breakfast in KK',
    'Airport Pickups & Park Vans',
    '[
      {"day": 1, "title": "Arrival in Kota Kinabalu", "desc": "Arrive in KK, transfer to your hotel. Spend the day visiting the KK Waterfront and night market."},
      {"day": 2, "title": "Kinabalu Park & Base Camp", "desc": "Transfer to Kinabalu National Park. Take a guided walk around the botanic gardens and check into your park lodge to acclimate."},
      {"day": 3, "title": "The Climb: Timpohon to Laban Rata", "desc": "Start the hike from Timpohon Gate. Trek through beautiful mossy forests up to Laban Rata Resthouse (3,272m). Enjoy dinner and rest early."},
      {"day": 4, "title": "Summit Sunrise & Return to KK", "desc": "Wake up at 2:00 AM. Ascend to Low''s Peak (4,095m) for a glorious sunrise. Descend to base camp, head back to KK, and celebrate at a local seafood dinner."},
      {"day": 5, "title": "Island Hopping & Departure", "desc": "Take a speed boat to Tunku Abdul Rahman Marine Park for snorkelling. Check out and head to KK airport for departure."}
    ]'::jsonb
  ),
  (
    'kuala-lumpur',
    '4D3N Kuala Lumpur City Discovery',
    'malaysian',
    450,
    '4 Days, 3 Nights',
    '/images/locations/kl.jpg',
    'Marvel at the Petronas Twin Towers, explore ancient Batu Caves, and experience vibrant street food and shopping.',
    true,
    'Kuala Lumpur, Malaysia',
    '4-Star City Center Hotel',
    'Daily Breakfast & 1 High Tea',
    'Hop-on Hop-off & Private Tours',
    '[
      {"day": 1, "title": "Arrival & Petronas Towers", "desc": "Arrive in KL. Visit the Skybridge at Petronas Twin Towers, then check out Bukit Bintang for shopping and dining."},
      {"day": 2, "title": "Batu Caves & Heritage Landmarks", "desc": "Climb the colorful 272 steps at Batu Caves. Later, tour Merdeka Square, Sultan Abdul Samad Building, and the National Mosque."},
      {"day": 3, "title": "Chinatown, Petaling Street & Local Food", "desc": "Discover historic Petaling Street, visit Kwai Chai Hong alleys, and enjoy a curated culinary tour testing local claypot rice and noodles."},
      {"day": 4, "title": "KL Tower & Departure", "desc": "Visit KL Tower Observation Deck for panoramic city photos. Shop at Central Market before transfer to KLIA."}
    ]'::jsonb
  ),
  (
    'kuantan',
    '3D2N Kuantan Beaches & Waterfalls',
    'malaysian',
    299,
    '3 Days, 2 Nights',
    '/images/locations/kuantan.jpg',
    'Relax on Cherating Beach, see the rainbow waterfalls of Sungai Lembing, and enjoy authentic seaside dining.',
    false,
    'Pahang, Malaysia',
    'Beachfront Resort Hotel',
    'Daily Breakfast',
    'Private Vehicle Transfers',
    '[
      {"day": 1, "title": "Arrival & Cherating Beach Sunset", "desc": "Arrive in Kuantan, check in to your beachfront resort. Take a stroll along Cherating Beach, visit the Turtle Sanctuary, and watch fireflies in the evening."},
      {"day": 2, "title": "Sungai Lembing Rainbow Waterfall", "desc": "Wake up early to catch a 4WD to the trailhead. Hike to the famous Rainbow Waterfall where sunlight forms a perfect rainbow in the mist. Visit the historical tin mines later."},
      {"day": 3, "title": "Teluk Cempedak & Departure", "desc": "Visit Teluk Cempedak for seaside photos, check out local crafts at Kuantan Art Street, and transfer back."}
    ]'::jsonb
  ),
  (
    'langkawi',
    '3D2N Langkawi Tropical Retreat',
    'malaysian',
    350,
    '3 Days, 2 Nights',
    '/images/locations/langkawi.jpg',
    'Duty-free shopping, cable car skybridge rides, and gorgeous sun-drenched beaches at this legendary archipelago.',
    true,
    'Langkawi, Kedah, Malaysia',
    '4-Star Beachside Resort',
    'Daily Breakfast',
    'Car Rental / Private Transfers',
    '[
      {"day": 1, "title": "Arrival & Pantai Cenang", "desc": "Arrive in Langkawi, check in at Cenang. Spend your afternoon relaxing on the beach or doing water sports. Stroll the duty-free malls in the evening."},
      {"day": 2, "title": "Langkawi Cable Car & SkyBridge", "desc": "Ride the Langkawi SkyCab up Machinchang Mountain. Walk on the SkyBridge suspended above the forest. Enjoy a mangrove boat tour in Kilim Geoforest Park afterwards."},
      {"day": 3, "title": "Eagle Square & Departure", "desc": "Take photos at the iconic Dataran Lang (Eagle Square) in Kuah Town. Shop for chocolates and souvenirs, then head to Langkawi Airport."}
    ]'::jsonb
  ),
  (
    'melaka',
    '3D2N Melaka Historical Heritage',
    'malaysian',
    299,
    '3 Days, 2 Nights',
    '/images/locations/melaka.jpg',
    'Take a trishaw ride through historical Dutch Square, cruise Melaka River, and enjoy unique Nyonya cuisine.',
    false,
    'Melaka, Malaysia',
    'Boutique Heritage Hotel',
    'Daily Breakfast & 1 Peranakan Lunch',
    'Walking Tours & River Cruise',
    '[
      {"day": 1, "title": "Arrival & Jonker Street Night Market", "desc": "Arrive in Melaka. Visit Jonker Street for shopping, antique hunting, and tasting local treats at the night market."},
      {"day": 2, "title": "UNESCO Heritage Sites & River Cruise", "desc": "Visit St. Paul''s Hill, A Famosa fort, and Christ Church in Dutch Square. In the evening, take a relaxing 45-minute Melaka River Cruise."},
      {"day": 3, "title": "Baba Nyonya Museum & Departure", "desc": "Tour the Baba & Nyonya Heritage Museum. Savour chicken rice balls and Nyonya laksa before departure."}
    ]'::jsonb
  ),
  (
    'pahang',
    '4D3N Pahang Jungle Expedition',
    'malaysian',
    699,
    '4 Days, 3 Nights',
    '/images/locations/pahang.jpg',
    'Journey deep into Taman Negara, walk the canopy bridge, and witness rich tropical rainforest flora and fauna.',
    false,
    'Taman Negara, Pahang, Malaysia',
    'Eco-Resort Jungle Lodge',
    'Full Board',
    'Wooden Boat Transfers & Guided Treks',
    '[
      {"day": 1, "title": "Arrival & Night Jungle Walk", "desc": "Depart from KL, take a boat from Kuala Tembeling to Taman Negara. Check in, and explore the forest at night with a guide to spot nocturnal insects and glowing mushrooms."},
      {"day": 2, "title": "Canopy Walkway & Bukit Teresek", "desc": "Walk the world''s longest canopy bridge. Hike up Bukit Teresek for a panoramic view of Mount Tahan. Take a boat to Lata Berkoh waterfalls in the afternoon."},
      {"day": 3, "title": "Orang Asli Settlement & Rapid Shooting", "desc": "Visit a local Bateq Orang Asli village to learn ancestral hunting and survival skills. Experience rapid shooting in a wooden boat."},
      {"day": 4, "title": "Check Out & Departure", "desc": "Leisurely breakfast listening to jungle sounds. Board the return boat and transfer back."}
    ]'::jsonb
  ),
  (
    'penang',
    '4D3N Penang Culinary Heritage',
    'malaysian',
    399,
    '4 Days, 3 Nights',
    '/images/locations/penang.jpg',
    'Voted top food city globally. Walk down historic Georgetown streets, visit Kek Lok Si Temple, and indulge in street food.',
    true,
    'Penang, Malaysia',
    '4-Star Georgetown Heritage Hotel',
    'Daily Breakfast & Street Food Tour voucher',
    'Heritage Trishaw & Private Tours',
    '[
      {"day": 1, "title": "Arrival & Street Art Hunt", "desc": "Arrive in Penang, check in. Spend the afternoon finding the famous street art murals in Georgetown. Enjoy dinner at Gurney Drive hawker center."},
      {"day": 2, "title": "Kek Lok Si Temple & Penang Hill", "desc": "Visit Kek Lok Si, the largest Buddhist temple in Malaysia. Take the funicular train up Penang Hill for spectacular sunset views of the island."},
      {"day": 3, "title": "Clan Jetties & Peranakan Mansion", "desc": "Explore the historic Chew Jetty houses on stilts, then tour the green Pinang Peranakan Mansion. Take an evening trishaw ride."},
      {"day": 4, "title": "Batu Ferringhi & Departure", "desc": "Visit the beaches of Batu Ferringhi, shop for local pastries (Tau Sar Piah), and transfer to the airport."}
    ]'::jsonb
  ),
  (
    'perak',
    '3D2N Perak Ipoh Heritage Tour',
    'malaysian',
    299,
    '3 Days, 2 Nights',
    '/images/locations/perak.jpg',
    'Discover cave temples, historical colonial structures, and sample famous Ipoh white coffee and local desserts.',
    false,
    'Ipoh, Perak, Malaysia',
    'Boutique Hotel',
    'Daily Breakfast',
    'Private Vehicle Transfers',
    '[
      {"day": 1, "title": "Arrival & Concubine Lane", "desc": "Arrive in Ipoh, check in. Walk through the historical Concubine Lane, tasting bean sprouts chicken and egg tarts."},
      {"day": 2, "title": "Kek Lok Tong & Kellie''s Castle", "desc": "Visit the magnificent Kek Lok Tong Cave Temple. Drive out to Kellie''s Castle, a mysterious unfinished mansion from the colonial era."},
      {"day": 3, "title": "Old Town Heritage & Departure", "desc": "Explore Birch Memorial Clock Tower, take photos at Ipoh Railway Station, and grab some Ipoh white coffee before heading home."}
    ]'::jsonb
  ),
  (
    'selangor',
    '3D2N Selangor Adventure & Theme Park',
    'malaysian',
    250,
    '3 Days, 2 Nights',
    '/images/locations/selangor.jpg',
    'Witness magical fireflies in Kuala Selangor, try white-water rafting, and explore the theme parks of Sunway Lagoon.',
    false,
    'Selangor, Malaysia',
    '4-Star City Hotel',
    'Daily Breakfast',
    'Private Transfers',
    '[
      {"day": 1, "title": "Arrival & Sunway Lagoon", "desc": "Check into your hotel. Spend a full day at Sunway Lagoon Theme Park, enjoying water rides, wildlife encounters, and extreme parks."},
      {"day": 2, "title": "Kuala Selangor Fireflies & Blue Tears", "desc": "Drive to Kuala Selangor. Climb Bukit Melawati, then take an evening boat ride to witness synchronized fireflies and the glowing blue tears phenomenon."},
      {"day": 3, "title": "Sky Mirror & Departure", "desc": "Take a boat to Sky Mirror sandbar during low tide for amazing reflective photography. Transfer back to the airport."}
    ]'::jsonb
  ),
  (
    'tasik-widuri',
    '3D2N Tasik Widuri Lakeside Escape',
    'malaysian',
    199,
    '3 Days, 2 Nights',
    '/images/locations/tasik.jpg',
    'Unwind at the serene lakeside resort of Tasik Widuri. Great for boat tours, fishing, and peaceful retreats.',
    false,
    'Perak, Malaysia',
    'Lakeside Resort Villa',
    'Daily Breakfast',
    'Private Transfers',
    '[
      {"day": 1, "title": "Arrival & Sunset Lake Cruise", "desc": "Arrive at Tasik Widuri and check into your lakeside villa. Enjoy a peaceful sunset pontoon boat ride around the lake."},
      {"day": 2, "title": "Fishing & Outdoor Recreational Activities", "desc": "Spend your day fishing, cycling around the scenic lake path, and enjoying the resort''s water park facilities."},
      {"day": 3, "title": "Leisure Morning & Departure", "desc": "Enjoy breakfast overlooking the mist rising from the lake. Relax and check out for departure."}
    ]'::jsonb
  ),
  (
    'dubai',
    '5D4N Dubai Desert Luxury Tour',
    'world',
    1499,
    '5 Days, 4 Nights',
    '/images/locations/dubai.jpg',
    'Ride camels in the Arabian desert, visit the Burj Khalifa observation deck, and explore grand shopping malls.',
    true,
    'Dubai, UAE',
    '5-Star Luxury Hotel',
    'Daily Breakfast & 1 Desert BBQ Dinner',
    '4WD Vehicles & Airport Transfers',
    '[
      {"day": 1, "title": "Arrival & Dhow Cruise Dinner", "desc": "Arrive in Dubai, transfer to your hotel. In the evening, enjoy a buffet dinner on a traditional wooden Dhow cruise along Dubai Creek."},
      {"day": 2, "title": "Burj Khalifa & Modern City Tour", "desc": "Explore modern Dubai. Visit Dubai Marina, Palm Jumeirah, and head up to the 124th floor of the Burj Khalifa. Shop at Dubai Mall."},
      {"day": 3, "title": "Desert Safari & BBQ Camp", "desc": "Hop into a 4WD for dune bashing in the desert. Ride camels, try sandboarding, and enjoy a Middle Eastern BBQ dinner under the stars with belly dancing performances."},
      {"day": 4, "title": "Old Dubai & Souk Exploration", "desc": "Cross the Dubai Creek by abra water taxi. Explore the Gold Souk and Spice Souk. Afternoon leisure or shopping."},
      {"day": 5, "title": "Miracle Garden & Departure", "desc": "Visit the world''s largest natural flower garden. Transfer to Dubai International Airport for departure."}
    ]'::jsonb
  ),
  (
    'europe',
    '10D9N Grand European Classics',
    'world',
    3499,
    '10 Days, 9 Nights',
    '/images/locations/europe.jpg',
    'Experience the romance of Paris, the historic Colosseum of Rome, and the spectacular snowcapped Swiss Alps.',
    true,
    'France, Switzerland, Italy',
    '4-Star Hotels throughout Europe',
    'Daily Breakfast & 4 dinners',
    'Luxury AC Tour Coach & Scenic Trains',
    '[
      {"day": 1, "title": "Arrive in Paris, France", "desc": "Arrive in Paris, check in. Enjoy a scenic evening cruise along the Seine River to see the Eiffel Tower lit up."},
      {"day": 2, "title": "Paris Landmarks & Louvre Museum", "desc": "Guided tour of Arc de Triomphe, Champs-Élysées, and visit the Louvre Museum. Afternoon leisure."},
      {"day": 3, "title": "Paris to Switzerland Scenic Drive", "desc": "Drive through beautiful French vineyards and check into your Swiss alpine lodge."},
      {"day": 4, "title": "Mount Titlis Snow Mountain", "desc": "Ride the Rotair revolving cable car up Mount Titlis (3,020m). Walk the glacier cave and cross the Titlis Cliff Bridge. Visit Lucerne later."},
      {"day": 5, "title": "Lucerne to Venice, Italy", "desc": "Drive past Lake Lugano, cross the border into Italy, and head to Venice."},
      {"day": 6, "title": "Venice Island Tour & Gondola Ride", "desc": "Take a private boat to St. Mark''s Square. Visit Doge''s Palace, watch a glassblowing demonstration, and take a traditional gondola cruise."},
      {"day": 7, "title": "Venice to Florence & Pisa", "desc": "Travel to Florence, the cradle of the Renaissance. Visit the Cathedral. Stop by the Leaning Tower of Pisa."},
      {"day": 8, "title": "Florence to Rome & Colosseum", "desc": "Travel to Rome. Tour the iconic Colosseum and see the Roman Forum."},
      {"day": 9, "title": "Vatican City & Trevi Fountain", "desc": "Visit St. Peter''s Basilica in the Vatican, throw a coin in the Trevi Fountain, and see the Spanish Steps."},
      {"day": 10, "title": "Departure from Rome", "desc": "Leisure morning for shopping. Transfer to Rome Fiumicino Airport for your flight back."}
    ]'::jsonb
  ),
  (
    'india',
    '7D6N India Golden Triangle Heritage',
    'world',
    1299,
    '7 Days, 6 Nights',
    '/images/locations/india.jpg',
    'Marvel at the majestic Taj Mahal in Agra, explore Jaipur''s Pink City palaces, and experience bustling Old Delhi.',
    false,
    'Delhi, Agra, Jaipur, India',
    '4-Star Heritage Hotels',
    'Daily Breakfast & 2 Dinners',
    'Private AC Chauffeured Sedan',
    '[
      {"day": 1, "title": "Arrival in New Delhi", "desc": "Arrive in Delhi and transfer to hotel. Rest of the day is at leisure."},
      {"day": 2, "title": "Delhi Sightseeing Tour", "desc": "Explore Old Delhi: Rickshaw ride at Chandni Chowk, see the Red Fort and Jama Masjid. Explore New Delhi: Qutub Minar, India Gate, and drive past Parliament House."},
      {"day": 3, "title": "Delhi to Agra & Agra Fort", "desc": "Drive to Agra. Check in and visit the magnificent Agra Fort. Enjoy sunset views of the Taj Mahal from across the Yamuna River."},
      {"day": 4, "title": "Taj Mahal Sunrise & Travel to Jaipur", "desc": "Visit the Taj Mahal at sunrise for stunning photo opportunities. Return for breakfast, then drive to Jaipur, visiting the ghost city Fatehpur Sikri enroute."},
      {"day": 5, "title": "Jaipur Pink City Palace Tour", "desc": "Visit Amer Fort on elephant/jeep. Later, see the Hawa Mahal (Palace of Winds), City Palace, and Jantar Mantar Observatory."},
      {"day": 6, "title": "Jaipur to Delhi & Shopping", "desc": "Drive back to Delhi. Spend the evening shopping at Connaught Place or Dilli Haat craft bazaar."},
      {"day": 7, "title": "Departure", "desc": "Transfer to Delhi Indira Gandhi International Airport for departure."}
    ]'::jsonb
  ),
  (
    'indonesia',
    '6D5N Bali Exotic Island Retreat',
    'world',
    799,
    '6 Days, 5 Nights',
    '/images/locations/bali.jpg',
    'Tour historic temples in Ubud, walk on volcanic black beaches, and witness stunning seaside cliff sunsets.',
    true,
    'Bali, Indonesia',
    'Beachfront Resort & Ubud Villa',
    'Daily Breakfast & 1 Jimbaran Seafood Dinner',
    'Private English-Speaking Driver/Guide',
    '[
      {"day": 1, "title": "Arrival in Bali & Uluwatu Cliff Temple", "desc": "Arrive in Denpasar, transfer to Kuta. In the afternoon, visit Uluwatu Temple perched on a 70m cliff, and watch a traditional Kecak fire dance."},
      {"day": 2, "title": "Kintamani Volcano & Ubud Heritage", "desc": "Trek up to Kintamani overlooking Mount Batur active volcano. Walk through Tegalalang Rice Terraces and explore Ubud Monkey Forest."},
      {"day": 3, "title": "Waterfalls & Tanah Lot Temple Sunset", "desc": "Visit Tegenungan Waterfall. Stop at the iconic Tanah Lot Temple, built on a rock out in the ocean, for a spectacular sunset."},
      {"day": 4, "title": "Nusa Penida Island Tour", "desc": "Take a speed boat to Nusa Penida. Visit Kelingking Beach (T-Rex Cliff), Broken Beach, and Angel''s Billabong."},
      {"day": 5, "title": "Ulun Danu Bratan Lake Temple", "desc": "Drive to Bedugul highlands to see the Ulun Danu temple floating on Lake Bratan. Dinner at Jimbaran Beach."},
      {"day": 6, "title": "Departure", "desc": "Leisurely morning around Kuta. Transfer to airport for flight."}
    ]'::jsonb
  ),
  (
    'korea',
    '6D5N Korea Seoul & Traditions',
    'world',
    1599,
    '6 Days, 5 Nights',
    '/images/locations/korea.jpg',
    'Explore historic palaces in Seoul, shop in Myeongdong, and experience the beautiful cherry blossoms of Jeju Island.',
    false,
    'Seoul & Jeju Island, South Korea',
    '4-Star City Hotels',
    'Daily Breakfast & 2 Lunches',
    'Domestic Flights & Subway Tours',
    '[
      {"day": 1, "title": "Arrival in Seoul", "desc": "Arrive at Incheon Airport, transfer to hotel in Seoul. Spend the evening visiting Namsan Seoul Tower."},
      {"day": 2, "title": "Gyeongbokgung Palace & Bukchon Hanok", "desc": "Watch the Changing of the Guard at Gyeongbokgung Palace, rent a traditional Hanbok, and stroll through Bukchon Hanok Village."},
      {"day": 3, "title": "Fly to Jeju Island", "desc": "Take a domestic flight to Jeju Island. Visit Yongduam Dragon Head Rock and stroll Hallasan park."},
      {"day": 4, "title": "Jeju Sunrise Peak & Waterfalls", "desc": "Climb Seongsan Ilchulbong (Sunrise Peak) for views of the crater. Visit Cheonjiyeon Waterfall and Seongeup Folk Village."},
      {"day": 5, "title": "Return to Seoul & Myeongdong Shopping", "desc": "Fly back to Seoul. Shop at Myeongdong market and enjoy local ginseng chicken soup."},
      {"day": 6, "title": "Nami Island & Departure", "desc": "Visit Nami Island (filming site of Winter Sonata) in Gapyeong. Transfer to Incheon Airport."}
    ]'::jsonb
  ),
  (
    'nepal',
    '7D6N Nepal Himalayan Expedition',
    'world',
    1099,
    '7 Days, 6 Nights',
    '/images/locations/nepal.jpg',
    'Hike near Pokhara lake, see Mount Everest ranges, and tour ancient temples in the historic city of Kathmandu.',
    true,
    'Kathmandu & Pokhara, Nepal',
    '3-Star / 4-Star Resort Hotels',
    'Daily Breakfast & 1 Cultural Dinner',
    'Private Tourist Coach',
    '[
      {"day": 1, "title": "Arrival in Kathmandu", "desc": "Arrive in Kathmandu, transfer to hotel. Enjoy a traditional Nepalese dinner and folk dances."},
      {"day": 2, "title": "Kathmandu UNESCO Sites", "desc": "Visit Boudhanath Stupa, Pashupatinath Hindu temple, and Swayambhunath (Monkey Temple)."},
      {"day": 3, "title": "Drive to Pokhara & Phewa Lake", "desc": "Scenic drive along Trisuli River to Pokhara. In the evening, enjoy a tranquil boat ride on Phewa Lake."},
      {"day": 4, "title": "Sarangkot Sunrise & Mountain views", "desc": "Drive to Sarangkot at 4:30 AM to see sunrise over the Annapurna ranges. Visit Davis Falls and Gupteshwor Cave later."},
      {"day": 5, "title": "Pokhara to Kathmandu & Patan City", "desc": "Drive back to Kathmandu. Stop at Patan Durbar Square to see medieval arts and architecture."},
      {"day": 6, "title": "Bhakthapur City Heritage", "desc": "Visit Bhaktapur Durbar Square, famous for woodcarvings and pottery. Afternoon free for trekking shopping."},
      {"day": 7, "title": "Departure", "desc": "Transfer to Kathmandu Tribhuvan Airport for your flight."}
    ]'::jsonb
  ),
  (
    'south-africa',
    '8D7N South Africa Wildlife Safari',
    'world',
    2499,
    '8 Days, 7 Nights',
    '/images/locations/southafrica.jpg',
    'Go on big-game safaris at Kruger National Park and ride the cableway to the summit of Table Mountain.',
    false,
    'Cape Town & Kruger Park, South Africa',
    '4-Star Safari Lodges & Cape Town Hotel',
    'Full Board on Safari, Breakfast in Cape Town',
    'Open Safari Vehicles & Domestic Flights',
    '[
      {"day": 1, "title": "Arrival in Cape Town", "desc": "Arrive in Cape Town and transfer to hotel. Rest of the day is at leisure."},
      {"day": 2, "title": "Table Mountain & City Tour", "desc": "Ride the Table Mountain Aerial Cableway (weather permitting) for views. Explore the Castle of Good Hope and colorful Bo-Kaap neighborhood."},
      {"day": 3, "title": "Cape Peninsula & Penguins", "desc": "Scenic drive along Chapman''s Peak. Visit Cape Point and the Cape of Good Hope. Stop at Boulders Beach to see the African penguin colony."},
      {"day": 4, "title": "Fly to Johannesburg & Kruger Lodge", "desc": "Take a flight to Johannesburg, then drive to a safari lodge on the border of Kruger National Park. Take an evening game drive."},
      {"day": 5, "title": "Full Day Kruger Safari", "desc": "Go on a sunrise safari in open 4x4 vehicles. Search for the Big Five (lion, leopard, elephant, rhino, buffalo) with park rangers. Dinner around a traditional Boma fire."},
      {"day": 6, "title": "Panorama Route Scenic Drive", "desc": "Drive the Panorama Route. See Blyde River Canyon, Bourke''s Luck Potholes, and God''s Window viewpoint."},
      {"day": 7, "title": "Johannesburg Soweto Tour", "desc": "Drive back to Johannesburg. Tour Soweto township, visiting Nelson Mandela''s former house."},
      {"day": 8, "title": "Check Out & Departure", "desc": "Visit the local craft market. Transfer to O.R. Tambo International Airport for departure."}
    ]'::jsonb
  ),
  (
    'thailand',
    '5D4N Amazing Thailand Explorer',
    'world',
    699,
    '5 Days, 4 Nights',
    '/images/locations/thailand.jpg',
    'Explore Bangkok''s grand palaces and reclining Buddhas, then relax on the world-class beaches of Phuket.',
    true,
    'Bangkok & Phuket, Thailand',
    '4-Star Resort Hotels',
    'Daily Breakfast',
    'Domestic Flights & Private Vans',
    '[
      {"day": 1, "title": "Arrival in Bangkok & River Cruise", "desc": "Arrive in Bangkok and transfer to hotel. Enjoy an evening dinner cruise along the Chao Phraya River."},
      {"day": 2, "title": "Grand Palace & Wat Pho", "desc": "Explore the Grand Palace and Emerald Buddha temple. Visit Wat Pho to see the massive Reclining Buddha. Afternoon shopping at MBK."},
      {"day": 3, "title": "Fly to Phuket & Beachfront Sunset", "desc": "Fly to Phuket. Check in at your resort and spend the evening watching the sunset over Patong Beach."},
      {"day": 4, "title": "Phi Phi Islands Speedboat Tour", "desc": "Board a speed boat to Phi Phi Ley. Snorkel in Maya Bay (filming site of The Beach), swim in Pileh Lagoon, and see Monkey Beach."},
      {"day": 5, "title": "Phuket Town & Departure", "desc": "Tour historic Sino-Portuguese Phuket Old Town. Transfer to Phuket Airport for your flight."}
    ]'::jsonb
  ),
  (
    'vietnam',
    '5D4N Vietnam Halong Bay Cruise',
    'world',
    599,
    '5 Days, 4 Nights',
    '/images/locations/vietnam.jpg',
    'Cruise through thousands of limestone islands in Halong Bay and walk heritage streets of Hanoi.',
    false,
    'Hanoi & Halong Bay, Vietnam',
    '4-Star Boutique Hotel & Cruise Cabin',
    'Daily Breakfast, 1 Lunch, 1 Seafood Dinner',
    'Cruiser Ship & AC Coach Transfers',
    '[
      {"day": 1, "title": "Arrival in Hanoi", "desc": "Arrive in Hanoi, check into hotel. Take a rickshaw (cyclo) tour around the Old Quarter and watch a traditional water puppet show."},
      {"day": 2, "title": "Hanoi City Tour & Travel to Halong Bay", "desc": "Visit Ho Chi Minh Mausoleum, One Pillar Pagoda, and the Temple of Literature. In the afternoon, drive through rural villages to Halong Bay."},
      {"day": 3, "title": "Halong Bay Overnight Cruise", "desc": "Board a luxury wooden junk cruise ship. Cruise past stunning karst stone towers. Explore Sung Sot (Surprise) Cave and kayak in quiet lagoons."},
      {"day": 4, "title": "Tai Chi & Return to Hanoi", "desc": "Start the day with Tai Chi on the deck. Cruise back to harbor, transfer back to Hanoi. Spend the evening shopping at Dong Xuan Market."},
      {"day": 5, "title": "Check Out & Departure", "desc": "Enjoy Vietnamese drip coffee by Hoan Kiem Lake. Transfer to Noi Bai International Airport for departure."}
    ]'::jsonb
  ),
  (
    'genting-tours',
    'Genting Tours',
    'sightseeing',
    68,
    '8 Hrs',
    '/images/transport/tour-1.jpg',
    'Full day tour to Genting Highlands with flexible free time at the resort.',
    false,
    'Malaysia',
    'N/A',
    'N/A',
    'Guided Vehicle',
    '[{"day": 1, "title": "Sightseeing", "desc": "Enjoy a guided sightseeing tour with hotel pick-up and drop-off."}]'::jsonb
  ),
  (
    'kuala-lumpur-night-tour',
    'Kuala Lumpur Night Tour',
    'sightseeing',
    34,
    '3 Hrs',
    '/images/transport/tour-2.jpg',
    'Experience the dazzling lights and vibrant nightlife of Kuala Lumpur.',
    false,
    'Malaysia',
    'N/A',
    'N/A',
    'Guided Vehicle',
    '[{"day": 1, "title": "Sightseeing", "desc": "Enjoy a guided sightseeing tour with hotel pick-up and drop-off."}]'::jsonb
  ),
  (
    'kuala-lumpur-city-tour',
    'Kuala Lumpur City Tour',
    'sightseeing',
    34,
    '3.5 Hrs',
    '/images/transport/tour-3.jpg',
    'Discover iconic KL landmarks including Petronas Towers and Batu Caves.',
    false,
    'Malaysia',
    'N/A',
    'N/A',
    'Guided Vehicle',
    '[{"day": 1, "title": "Sightseeing", "desc": "Enjoy a guided sightseeing tour with hotel pick-up and drop-off."}]'::jsonb
  ),
  (
    'kl-country-tour',
    'KL Country Tour',
    'sightseeing',
    34,
    '4 Hrs',
    '/images/transport/tour-4.jpg',
    'Explore the natural beauty and rural charm surrounding Kuala Lumpur.',
    false,
    'Malaysia',
    'N/A',
    'N/A',
    'Guided Vehicle',
    '[{"day": 1, "title": "Sightseeing", "desc": "Enjoy a guided sightseeing tour with hotel pick-up and drop-off."}]'::jsonb
  ),
  (
    'melaka-tour',
    'Melaka Tour',
    'sightseeing',
    113,
    '8 Hrs',
    '/images/transport/tour-5.jpg',
    'Full day tour of Melaka covering Dutch Square, A Famosa, and Jonker Street.',
    false,
    'Malaysia',
    'N/A',
    'N/A',
    'Guided Vehicle',
    '[{"day": 1, "title": "Sightseeing", "desc": "Enjoy a guided sightseeing tour with hotel pick-up and drop-off."}]'::jsonb
  ),
  (
    'dinner-transfer',
    'Dinner Transfer',
    'sightseeing',
    27,
    'Evening',
    '/images/transport/tour-6.jpg',
    'Round-trip transfer to popular dining destinations in KL.',
    false,
    'Malaysia',
    'N/A',
    'N/A',
    'Guided Vehicle',
    '[{"day": 1, "title": "Sightseeing", "desc": "Enjoy a guided sightseeing tour with hotel pick-up and drop-off."}]'::jsonb
  )
on conflict (slug) do nothing;
